# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dohody.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(879, 600)
        MainWindow.setStyleSheet("#MainWindow {border-image: url(C:/Users/UFK/Documents/GitHub/dohody_project/img/fon.jpg);}\n"
"\n"
".QMenuBar{background-color: #444444;color: white;} \n"
".QMenuBar:item:selected{background: #444444;color: #fcf605;}\n"
".QMenu {background-color: #444444;color: white;} \n"
".QMenu:item:selected{background: #444444;color: #fcf605;} \n"
"\n"
"\n"
".QStatusBar{background-color: #444444;color: white;}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMaximumSize(QtCore.QSize(40, 40))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("roskazna.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.open_file_one = QtWidgets.QPushButton(self.centralwidget)
        self.open_file_one.setMinimumSize(QtCore.QSize(0, 40))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open_file_one.setIcon(icon)
        self.open_file_one.setIconSize(QtCore.QSize(30, 30))
        self.open_file_one.setObjectName("open_file_one")
        self.horizontalLayout.addWidget(self.open_file_one)
        self.status_one = QtWidgets.QLabel(self.centralwidget)
        self.status_one.setMinimumSize(QtCore.QSize(0, 40))
        self.status_one.setMaximumSize(QtCore.QSize(40, 16777215))
        self.status_one.setText("")
        self.status_one.setPixmap(QtGui.QPixmap("img/stop.png"))
        self.status_one.setScaledContents(True)
        self.status_one.setObjectName("status_one")
        self.horizontalLayout.addWidget(self.status_one)
        self.open_file_two = QtWidgets.QPushButton(self.centralwidget)
        self.open_file_two.setMinimumSize(QtCore.QSize(0, 40))
        self.open_file_two.setIcon(icon)
        self.open_file_two.setIconSize(QtCore.QSize(30, 30))
        self.open_file_two.setObjectName("open_file_two")
        self.horizontalLayout.addWidget(self.open_file_two)
        self.status_two = QtWidgets.QLabel(self.centralwidget)
        self.status_two.setMinimumSize(QtCore.QSize(0, 40))
        self.status_two.setMaximumSize(QtCore.QSize(40, 16777215))
        self.status_two.setText("")
        self.status_two.setPixmap(QtGui.QPixmap("img/stop.png"))
        self.status_two.setScaledContents(True)
        self.status_two.setWordWrap(False)
        self.status_two.setObjectName("status_two")
        self.horizontalLayout.addWidget(self.status_two)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.save = QtWidgets.QPushButton(self.centralwidget)
        self.save.setMinimumSize(QtCore.QSize(0, 40))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save.setIcon(icon1)
        self.save.setIconSize(QtCore.QSize(30, 30))
        self.save.setObjectName("save")
        self.horizontalLayout.addWidget(self.save)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.table = QtWidgets.QTableWidget(self.centralwidget)
        self.table.setStyleSheet(".QTableWidget {background-color: rgba(0, 0, 0, 100);\n"
"border-radius:8px; color: white; font: bold;}")
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        self.verticalLayout.addWidget(self.table)
        self.verticalLayout.setStretch(1, 5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 879, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.menu.addAction(self.action)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.open_file_one.setText(_translate("MainWindow", "Загрузить таблицу 1"))
        self.open_file_two.setText(_translate("MainWindow", "Загрузить таблицу 2"))
        self.save.setText(_translate("MainWindow", "Сохранить в Excel"))
        self.menu.setTitle(_translate("MainWindow", "О программе"))
        self.action.setText(_translate("MainWindow", "О программе"))
